### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Elgressik** [achubutkin/yandex-games-sdk-gdevelop-extension#2]
Здраствуйте. Нет функции возврата языка от яндекс sdk. Могли бы вы добавить его?

**Comment by achubutkin** [comment]
@Elgressik Привет, добавил. Версия 2.5. 

Язык можно получить через переменные окружения, вызови экшен Get Environment Variables и укажи имя глобальной переменной. Затем из этой переменной будет доступен язык через GlobalVariableString(ИмяПеременной["i18n"]["lang"]).
